name: Sign Devices

on:
  push:
    paths:
      - 'devices/devices.json'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Calculate HMAC
        env:
          SECRET_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "Calculating HMAC-SHA256..."
          DEVICES_JSON=$(jq -c .devices devices/devices.json)
          SIGNATURE=$(echo -n "$DEVICES_JSON" | openssl dgst -sha256 -hmac "$SECRET_KEY" -binary | base64)
          jq --arg sig "$SIGNATURE" '.signature = $sig' devices/devices.json > temp.json
          mv temp.json devices/devices.json
          
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-sign devices"
