name: Update Signature

on:
  push:
    paths:
      - 'devices/devices.json'
      
jobs:
  update-signature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Calculate SHA256
        id: hash
        run: |
          JSON_DATA=$(jq -c .devices devices/devices.json)
          SIGNATURE=$(echo -n "$JSON_DATA${{ secrets.SIGNING_KEY }}" | sha256sum | cut -d' ' -f1)
          echo "signature=$SIGNATURE" >> $GITHUB_OUTPUT
          
      - name: Update Signature
        run: |
          jq --arg sig "${{ steps.hash.outputs.signature }}" '.signature = $sig' devices/devices.json > tmp.json
          mv tmp.json devices/devices.json
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update signature"
